import Image from 'next/image';
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-slate-400'>
          <section className='flex justify-between max-w-7xl mx-auto py-6 bg-slate-300'>
            <div className='flex gap-6 bg-slate-200'>
              <Image src="/next.svg" alt="Chest.js" width="100" height="100" />
              <Link className='hover:text-white transition-all duration-500' href="/">Link</Link>
              <Link className='hover:text-white' href="/">Link</Link>
              <Link className='hover:text-white' href="/">Link</Link>
              <Link className='hover:text-white' href="/">Link</Link>
              <Link className='hover:text-white' href="/">Link</Link>
            </div>

            <div className='flex gap-6 bg-slate-200'>
              <span>Search</span>
              <span>Profile</span>
            </div>
          </section>
        </header>

        {children}
        
        <footer className='bg-black'>
          <section className="flex justify-between max-w-7xl mx-auto py-6">

          </section>
        </footer>
      </body>
    </html>
  )
}
